/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class FizzBuzz {
	
	private String response = ""; 
	
    public void processNum(int num) {
    		if (num == 0) { 
    			setResponse(Integer.toString(num)); 
    		} else {
    			if (num % 3 == 0) setResponse("fizz");
    	        if (num % 5 == 0) setResponse("buzz");
    	        if (response == "") setResponse(Integer.toString(num));
    		}
    }
    
    public void setResponse(String string) {
    		response += string;
    }
    
    public String getResponse() {
    		return response;
    }
}
